name: delpoy to s3
on: 
    push:
        branches: 
            - main
            - release/**
            - features/**
    pull_request: 
        branches: 
            - main
    workflow_dispatch:                

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: build step
              run: echo "building..."
            - name: final check
              run: echo "finalizing..."
            - name: checking vars
              run: echo "variable is ${{vars.MY_VAR}}"  
            - name: checking secrets
              run: echo "secrets is ${{secrets.DOCKER_PASS}}"  
    action:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: checkout code
              run:             
