name: greeting
on: 
  push:
    branches: 
      - main
      - "release/**"  
    paths-ignore:  
      - '.gitignore'
      - '/github/workflows/*'
  pull_request: 
    branches: 
      - main 
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "build..."
      - name: final step 
        run: echo "finalize2..."
  check_variable:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: getting variable
        run: echo "getting..."
      - name: showing variable
        run: echo "hello, ${{vars.MY_VAR}}"
